import time
import allure
from base.base_test import BaseTest

@allure.epic("Основная функция сайта")
@allure.feature("Покупка авторизованным пользователем")
@allure.severity(allure.severity_level.CRITICAL)
@allure.description("Здесь по идее можно написать какое-то описание")
@allure.tag("smoke", "regression", "ui")
class TestLoginBuyLogout(BaseTest):

    @allure.title("Авторизация, покупка, разлогин")
    @allure.id(1)
    @allure.story("Покупка товара")
    @allure.suite("Тест на проверку покупки авторизованным пользователем и разлогин")
    def test_login_buy_logout(self):
        self.login_page.open()
        self.login_page.is_opened()
        self.login_page.enter_login(login=self.credentials.LOGIN)
        self.login_page.enter_password(password=self.credentials.PASSWORD)
        self.login_page.click_login_button()
        self.inventory_page.is_opened()
        self.inventory_page.click_button_bike_light_add_to_cart()
        self.inventory_page.click_cart_button()
        self.cart_page.is_opened()
        self.cart_page.is_bike_light_displayed()
        self.cart_page.click_checkout_button()
        self.checkout_step_one_page.is_opened()
        self.checkout_step_one_page.enter_first_name_field()
        self.checkout_step_one_page.enter_last_name_field()
        self.checkout_step_one_page.enter_postal_code_field()
        self.checkout_step_one_page.click_continue_button()
        self.checkout_step_two_page.is_opened()
        self.checkout_step_two_page.click_finish_button()
        self.checkout_complete_page.is_opened()
        self.checkout_complete_page.click_back_home_button()
        self.inventory_page.is_opened()
        self.inventory_page.click_sidebar_burger_button()
        self.inventory_page.click_logout_button_in_sidebar()
        self.login_page.is_opened()